services:
  - type: web
    name: My-Webhook-Monitor
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node app.js'
    envVars:
      - key: NODE_ENV
        value: production
    secrets:
      - key: PORT
        value: $PORT